WebApplication1/Controllers/SetUpController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers

{
    [CheckSession]
    public class SetUpController : Controller
    {
        ArchitectureEntitiesModel entities = new ArchitectureEntitiesModel();
        EshtiracksType Eshtirackstype = new EshtiracksType();
        // GET: SetUp
        [HttpGet]
        public ActionResult TypesofEstiracks()
        {
            TempData["Heading"] = 1;
            try {
                TempData["TypesofSubsription"] = entities.EshtiracksTypes.OrderByDescending(e => e.Id).ToList();

                return View();
                
            }
            catch(Exception ex)
            {
           

                return View();
            }
            
        }

        [HttpPost]
        public ActionResult TypesofEstiracks(EshtiracksType Eshtirackstype)
        {
            try {

                if (ModelState.IsValid)
                {

                    using (ArchitectureEntitiesModel entities = new ArchitectureEntitiesModel())
                    {
                        entities.EshtiracksTypes.Add(Eshtirackstype);
                        entities.SaveChanges();
                        int id = Eshtirackstype.Id;
                        if (id > 0)
                        {
                            TempData["Success"] = "Successfully Saved";
                        }
                        else
                        {
                            TempData["Failed"] = "Not Saved";
                        }

                    }
                }
            }
            catch(Exception ex)
            {
                TempData["Failed"] = "Exception Occured";
                return View();
            }
            
            return RedirectToAction("TypesofEstiracks");      
        }

        public ActionResult EditTypesofEstiracks(Int32 id)  
        {
            EshtiracksType TypesofEstiracks = new EshtiracksType();
           try {
                TypesofEstiracks = entities.EshtiracksTypes.Where(x => x.Id == id).FirstOrDefault();

                if (TypesofEstiracks != null)
                {
                    ViewBag.Id = id;
                    TempData["Heading"] = 1;

                }
            }
            catch (Exception ex)
            {

            }
            
            return View(TypesofEstiracks);
        }

        [HttpPost]
        public ActionResult UpdateTypesofEstirack(EshtiracksType Eshtirackstype)
        {
            try
            {
                using (ArchitectureEntitiesModel entities = new ArchitectureEntitiesModel())
                {
                    EshtiracksType updatedTypesofEstiracks = (from c in entities.EshtiracksTypes
                                                              where c.Id == Eshtirackstype.Id
                                                              select c).FirstOrDefault();
                    updatedTypesofEstiracks.Description = Eshtirackstype.Description;
                    updatedTypesofEstiracks.Amount = Eshtirackstype.Amount;
                    entities.SaveChanges();
                    int id = Eshtirackstype.Id;
                    if (id > 0)
                    {
                        TempData["Success"] = "Successfully Updated";
                        TempData["Heading"] = 1;
                        return RedirectToAction("TypesofEstiracks");
                    }
                    else
                    {
                        TempData["Failed"] = "Not Updated";
                        return View();
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["Failed"] = "Exception Occured";
                return View();
            }
           

            
        }


    
        public ActionResult DeleteEstriacksTypes(int ? id)
        {
            try {
                if (id != null)
                {
                    var eshtiracksType = entities.EshtiracksTypes.SingleOrDefault(e => e.Id == id);
                    var checktype = entities.ClientsViews.SingleOrDefault(e => e.Type == id);
                    if (checktype == null)
                    {
                        entities.EshtiracksTypes.Remove(eshtiracksType ?? throw new InvalidOperationException());
                        entities.SaveChanges();
                        TempData["Success"] = "Successfully Deleted";
                        return RedirectToAction("TypesofEstiracks");
                    }
                    else
                    {
                        TempData["Error"] = "Subscription type is using by " +checktype.Name+". Cannot delete subscription type " + eshtiracksType.Description;
                    }

                }
            }
            catch (Exception ex)
            {


            }
           
            return RedirectToAction("TypesofEstiracks");
        }
        public ActionResult ExpensesListNames()
       {
            try {
                using (ArchitectureEntitiesModel ObjEntities = new ArchitectureEntitiesModel())
                {
                    var getexpenselist = ObjEntities.ExpenseListNames.OrderByDescending(e => e.Id).ToList();
                    if (getexpenselist.Count != 0)
                    {
                        List<ExpenseListVM> Expenselist = new List<ExpenseListVM>();
                        foreach (var i in getexpenselist)
                        {
                            ExpenseListVM v = new ExpenseListVM();
                            v.Id = i.Id;
                            v.Description = i.Description;
                            v.IconPath = i.IconPath;
                            Expenselist.Add(v);


                        }
                       
                        TempData["Expenselist"] = Expenselist;
                    }
                }
            }
            catch (Exception ex)
            {

            }

            TempData["Heading"] = 2;

            return View();
        }

        [HttpPost]
        public ActionResult ExpensesListNames(ExpenseListName expenselistname,HttpPostedFileBase postedFile)
        {
            try {
                if (postedFile != null)
                {
                    string filename = Path.GetFileName(postedFile.FileName);

                    string extension = Path.GetExtension(postedFile.FileName);


                    expenselistname.IconPath = "~/Images/avatars/" + filename;


                    filename = Path.Combine(Server.MapPath("~/Images/avatars/"), filename);

                    postedFile.SaveAs(filename);

                    entities.ExpenseListNames.Add(expenselistname);

                    entities.SaveChanges();

                    int id1 = expenselistname.Id;
                    TempData["Heading"] = 2;
                    if (id1 > 0)
                    {
                        TempData["Success"] = "Successfully Saved";
                    }
                    else
                    {
                        TempData["Failed"] = "Not Saved";
                    }

                    return RedirectToAction("ExpensesListNames");
                }
                // entities.Entry(expenselistname).State = EntityState.Modified;
                expenselistname.IconPath = "";
                entities.ExpenseListNames.Add(expenselistname);
                entities.SaveChanges();
                int id = expenselistname.Id;
                TempData["Heading"] = 2;
                if (id > 0)
                {
                    TempData["Success"] = "Successfully Saved";
                }
                else
                {
                    TempData["Failed"] = "Not Saved";
                }
            }
            catch (Exception ex)
            {

            }
            

            return RedirectToAction("ExpensesListNames");
        }
           
    

        public ActionResult EditExpenseListNames(Int32 id)
        {
            try {
                var expenseListName = entities.ExpenseListNames.Where(x => x.Id == id).FirstOrDefault();
                if (expenseListName != null)
                {
                    ViewBag.Id = id;
                    return View(expenseListName);
                }
                TempData["Heading"] = 2;
            }
            catch (Exception ex)
            {

            }
            return View(entities.EshtiracksTypes.ToList());
        }

        [HttpPost]
        public ActionResult UpdateExpensesListNames(ExpenseListName expenselistname, HttpPostedFileBase ImageFile)
        {
            try {
                using (ArchitectureEntitiesModel entities = new ArchitectureEntitiesModel())
                {
                    ExpenseListName updatedexpenselistname = (from c in entities.ExpenseListNames
                                                              where c.Id == expenselistname.Id
                                                              select c).FirstOrDefault();

                    updatedexpenselistname.Description = expenselistname.Description;

                    //expenselistname.ImageFile = new HttpPostedFile();
                    //Extract Image File Name.

                    if (ImageFile != null)
                    {

                        string fileName = System.IO.Path.GetFileName(ImageFile.FileName);
                        // Set the Image File Path.
                        string filePath = "~/Images/avatars/" + fileName;

                        //Save the Image File in Folder.
                        ImageFile.SaveAs(Server.MapPath(filePath));

                        updatedexpenselistname.IconPath = filePath;

WebApplication1/Views/SetUp/EditExpenseListNames.cshtml
@model WebApplication1.ExpenseListName
@{
    ViewBag.Title = "EditExpensesListName";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Success"] != null)
{
    <div id="Success">
        <div class="alert alert-success fade show" role="alert">
            @TempData["Success"]
        </div>
    </div>

}
@if (TempData["Error"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Error"]
        </div>
    </div>
}

@if (TempData["Failed"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Failed"]
        </div>
    </div>
}

@using (Html.BeginForm("UpdateExpensesListNames", "SetUp", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))

{

    <div class="tab-content">
        <div class="tab-pane tabs-animation fade show active" id="tab-content-0" role="tabpanel">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <h5 class="card-title">Update Expense</h5>
                    @if (TempData["Success"] != null)
                    {

                        <div class="alert-success fade show" role="alert">
                            @TempData["Success"]
                        </div>

                    }
                    <form class="">
                        <div class="form-row">
                            @Html.HiddenFor(m => m.Id)
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.TextBoxFor(m => m.Description, Model.Description, new { @type = "text", placeholder = "Enter Description at here ", @class = "form-control", required = "required" })
                                    @*@Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })*@
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.TextBoxFor(m => m.IconPath, Model.IconPath.ToString(), new { @type = "file", @Name = "ImageFile", placeholder = "Enter file at here ", @class = "form-control" })
                                    @*@Html.ValidationMessageFor(m => m.IconPath, "", new { @class = "text-danger" })*@

                                </div>
                            </div>
                        </div>
                        <button class="mt-2 btn btn-primary">Update</button>
                    </form>
                </div>

            </div>

        </div>
    </div>
}
<script>
    $(document).ready(function () {
        setTimeout(function () {
            $("#Success").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Error").fadeOut();
        }, 5000);
    });

</script>

WebApplication1/Views/SetUp/EditTypesofEstiracks.cshtml
@model WebApplication1.EshtiracksType
@{
    ViewBag.Title = "Edit Types of Estiracks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Success"] != null)
{
    <div id="Success">
        <div class="alert alert-success fade show" role="alert">
            @TempData["Success"]
        </div>
    </div>

}
@if (TempData["Error"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Error"]
        </div>
    </div>
}

@if (TempData["Failed"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Failed"]
        </div>
    </div>
}

@using (Html.BeginForm("UpdateTypesofEstirack", "SetUp", FormMethod.Post))
{

    <div class="tab-content">
        <div class="tab-pane tabs-animation fade show active" id="tab-content-0" role="tabpanel">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <h5 class="card-title">Update Subscription</h5>
                    @if (TempData["Success"] != null)
                    {

                        <div class="alert-success" role="alert">
                            @TempData["Success"]
                        </div>

                    }
                    <form class="">
                        <div class="form-row">
                            @Html.HiddenFor(m => m.Id)
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.TextBoxFor(m => m.Description, Model.Description, new { @type = "text", placeholder = "Enter Description at here ", @class = "form-control", required = "required" })
                                    @*@Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })*@
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.TextBoxFor(m => m.Amount, Model.Amount.ToString(), new { @type = "number", placeholder = "Enter Amount at here ", @class = "form-control", required = "required" })
                                    @*@Html.ValidationMessageFor(m => m.Amount, "", new { @class = "text-danger" })*@

                                </div>
                            </div>
                        </div>
                        <button class="mt-2 btn btn-primary">Update</button>
                    </form>
                </div>

            </div>

        </div>
    </div>
}

<script>
    $(document).ready(function () {
        setTimeout(function () {
            $("#Success").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Error").fadeOut();
        }, 5000);
    });

</script>

WebApplication1/Views/SetUp/ExpensesListNames.cshtml
@model WebApplication1.ExpenseListName
@{
    ViewBag.Title = "Expenses List Name";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Success"] != null)
{
    <div id="Success">
        <div class="alert alert-success fade show" role="alert">
            @TempData["Success"]
        </div>
    </div>

}
@if (TempData["Error"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Error"]
        </div>
    </div>
}

@if (TempData["Failed"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Failed"]
        </div>
    </div>
}

@using (Html.BeginForm("ExpensesListNames", "SetUp", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{
    <div class="tab-content">
        <div class="tab-pane tabs-animation fade show active" id="tab-content-0" role="tabpanel">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <h5 class="card-title">Add Expense </h5>

                    <form class="">

                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.TextBoxFor(m => m.Description, "", new { @type = "text", placeholder = "Enter Description at here ", @class = "form-control", required = "required" })
                                    @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    <input type="file" name="postedFile" ,required="required" />
                                </div>
                            </div>
                        </div>
                        <button class="mt-2 btn btn-primary">Add</button>
                    </form>
                </div>
                <div class="form-row">
                    <div class="col-lg-12">
                        <div class="main-card mb-3 card">
                            <div class="card-body">
                                <h5 class="card-title">Expense Lists</h5>
                                <table class="mb-0 table table-bordered">
                                    <thead>
                                        <tr>

                                            <th>Description</th>
                                            <th>Icon Image</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>


                                    <tbody>
                                        @if (TempData["Expenselist"] != null)
                                        {
                                            foreach (var E in (List<WebApplication1.ViewModel.ExpenseListVM>)TempData["Expenselist"])
                                            {
                                                <tr>

                                                    <td>@E.Description</td>
                                                    @if (@E.IconPath.Equals(string.Empty))
                                                    {
                                                        <td>
                                                            <img width="42" class="rounded-circle" src="" alt="">
                                                        </td>
                                                    }
                                                    else
                                                    {
                                                        <td><img width="42" class="rounded-circle" src="@Url.Content(E.IconPath)" alt=""></td>
                                                    }

                                                    <td>
                                                        |<a href="@Url.Action("EditExpenseListNames", "SetUp", new { id = E.Id })"><i class="fa fa-edit text-default"></i></a>|
                                                        |<a href="@Url.Action("DeleteExpenseList", "SetUp", new { id = E.Id })"><i class="fa fa-trash text-danger"></i></a>|
                                                    </td>
                                                </tr>
                                            }
                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>


}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        setTimeout(function () {
            $("#Success").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Error").fadeOut();
        }, 5000);
    });

</script>

WebApplication1/Views/SetUp/TypesofEstiracks.cshtml
@model WebApplication1.EshtiracksType
@{
    ViewBag.Title = "Types of Subscriptions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Success"] != null)
{
    <div id="Success">
        <div class="alert alert-success fade show" role="alert">
            @TempData["Success"]
        </div>
    </div>

}
@if (TempData["Error"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Error"]
        </div>
    </div>
}

@if (TempData["Failed"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Failed"]
        </div>
    </div>
}



@using (Html.BeginForm("TypesofEstiracks", "SetUp", FormMethod.Post))
{

    <div class="tab-content">
        <div class="tab-pane tabs-animation fade show active" id="tab-content-0" role="tabpanel">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <h5 class="card-title"> Add Subscription</h5>

                    <form class="">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.TextBoxFor(m => m.Description, " ", new { @type = "text", placeholder = "Enter Description at here ", @class = "form-control", required = "required", title = "Enter Description" })
                                    @*@Html.ValidationMessageFor(m => m.Description)*@
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.TextBoxFor(m => m.Amount, " ", new { @type = "number", placeholder = "Enter Amount at here ", @class = "form-control", required = "required" })
                                    @*@Html.ValidationMessageFor(m => m.Amount, "", new { @class = "text-danger" })*@

                                </div>
                            </div>
                        </div>
                        <button class="mt-2 btn btn-primary">Add</button>
                    </form>
                </div>
                <div class="form-row">
                    <div class="col-lg-12">
                        <div class="main-card mb-3 card">
                            <div class="card-body">
                                <h5 class="card-title">Types of Subscription</h5>
                                <table class="mb-0 table table-bordered">
                                    <thead>
                                        <tr>

                                            <th>Description</th>
                                            <th>Amount</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (TempData["TypesofSubsription"] != null)
                                        {
                                            foreach (var E in (List<WebApplication1.EshtiracksType>)TempData["TypesofSubsription"])
                                            {
                                                <tr>

                                                    <td>@E.Description</td>
                                                    <td>@E.Amount</td>
                                                    <td>
                                                        |<a href="@Url.Action("EditTypesofEstiracks", "SetUp", new { id = E.Id })"><i class="fa fa-edit text-default"></i></a>|
                                                        |<a href="@Url.Action("DeleteEstriacksTypes", "SetUp", new { id = E.Id })"><i class="fa fa-trash text-danger"></i></a>|
                                                    </td>
                                                </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                                @*<div class="modal fade" id="basic" tabindex="-1" role="banner" aria-hidden="true" style="display: none;">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                                    <h4 class="modal-title">Delete Confirmation</h4>
                                                </div>
                                                <div class="modal-body">
                                                    Are you sure you want to delete this item?
                                                </div>
                                                <div class="modal-footer">
                                                    <button data-dismiss="modal" type="button" class="btn btn-default">Cancel</button>
                                                    <button id="btnContinueDelete" type="button" class="btn btn-primary">Delete</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>*@
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        setTimeout(function () {
            $("#Success").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Error").fadeOut();
        }, 5000);
    });

</script>