WebApplication1/Controllers/RecapPagesController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity.SqlServer;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers
{
    [CheckSession]
    public class RecapPagesController : Controller
    {

        ArchitectureEntitiesModel ObjEntities = new ArchitectureEntitiesModel();
        int isfilter = 0;
        DataSet dsfilter = new DataSet();
        // GET: RecapPages
        public ActionResult Recappermonth()
        {
            DataSet ds = new DataSet();
            DataTable dt = new DataTable();
            try {
               
                string constr = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;

                using (ArchitectureEntitiesModel ObjEntities = new ArchitectureEntitiesModel())
                {
                    var GetMonth = new SelectList(ObjEntities.tblMonths.ToList(), "Id", "Month");

                    ViewData["GetMonth"] = GetMonth;

                }
                using (SqlConnection con = new SqlConnection(constr))
                {
                    string query = "Select FORMAT(E.MonthDate,'MMMM') as Month, Sum(cast(C.[Paid Amount] as float(10))) as Income,isnull(E.Amount, 0) as Expense from ClientsPayment as C inner join ClientsExpense as E on Month(E.MonthDate)= Month(C.Month) group by C.Month, E.MonthDate,E.Amount order by C.Month";
                    using (SqlCommand cmd = new SqlCommand(query))
                    {
                        cmd.Connection = con;
                        using (SqlDataAdapter sda = new SqlDataAdapter(cmd))
                        {
                            sda.Fill(dt);
                        }

                        DataColumn newCol = new DataColumn("NetAmount", typeof(Int64));
                        dt.Columns.Add(newCol);

                        foreach (DataRow row in dt.Rows)
                        {
                            Int64 Income = Int64.Parse(row.ItemArray[1].ToString());
                            Int64 expense = Int64.Parse(row.ItemArray[2].ToString());

                            row["NetAmount"] = Income - expense;

                        }
                        ds.Tables.Add(dt);
                    }
                }
                TempData["Heading"] = 6;
            }
            catch(Exception ex) { }
            
            return View(ds);
        }

        [HttpPost]
        public ActionResult Recappermonth(FormCollection Form)
        {
            DataSet ds = new DataSet();
            DataTable dt = new DataTable();
            try
            {
                string constr = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;

                using (ArchitectureEntitiesModel ObjEntities = new ArchitectureEntitiesModel())
                {
                    var GetMonth = new SelectList(ObjEntities.tblMonths.ToList(), "Id", "Month");

                    ViewData["GetMonth"] = GetMonth;

                }
                using (SqlConnection con = new SqlConnection(constr))
                {
                    string selectmonth = Request.Form["Month"].ToString();
                    string query = "Select FORMAT(E.MonthDate,'MMMM') as Month, Sum(cast(C.[Paid Amount] as float(10))) as Income,isnull(E.Amount, 0) as Expense from ClientsPayment as C inner join ClientsExpense as E on Month(E.MonthDate)= Month(C.Month)  where Month(E.MonthDate)=" + selectmonth + " group by C.Month, E.MonthDate,E.Amount order by C.Month";
                    using (SqlCommand cmd = new SqlCommand(query))
                    {
                        cmd.Connection = con;
                        using (SqlDataAdapter sda = new SqlDataAdapter(cmd))
                        {
                            sda.Fill(dt);
                        }

                        DataColumn newCol = new DataColumn("NetAmount", typeof(Int64));
                        dt.Columns.Add(newCol);

                        foreach (DataRow row in dt.Rows)
                        {
                            Int64 Income = Int64.Parse(row.ItemArray[1].ToString());
                            Int64 expense = Int64.Parse(row.ItemArray[2].ToString());

                            row["NetAmount"] = Income - expense;

                        }
                        ds.Tables.Add(dt);
                    }
                }
                TempData["Heading"] = 6;
            }
            catch(Exception ex) { }
          
           
            return View(ds);
        }

        public ActionResult Recapperexpensetype()
        {
            DataSet ds = new DataSet();
            DataTable dt = new DataTable();
            try
            {
                

                using (ArchitectureEntitiesModel ObjEntities = new ArchitectureEntitiesModel())
                {
                    var ClientExpense = new SelectList(ObjEntities.ExpenseListNames.ToList(), "Id", "Description");

                    ViewData["ClientExpense"] = ClientExpense;

                }
                string constr = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
                using (SqlConnection con = new SqlConnection(constr))
                {
                    string query = "Select * from ClientsExpense as C inner join ExpenseListNames as E on E.Id=C.Expensetype";
                    using (SqlCommand cmd = new SqlCommand(query))
                    {
                        cmd.Connection = con;
                        using (SqlDataAdapter sda = new SqlDataAdapter(cmd))
                        {
                            sda.Fill(dt);
                        }

                        ds.Tables.Add(dt);
                    }
                }
                TempData["Heading"] = 7;
            }
            catch (Exception ex) { }
          
            return View(ds);
        }
        [HttpPost]
        public ActionResult Recapperexpensetype(FormCollection Form)
        {
            DataSet ds = new DataSet();
            DataTable dt = new DataTable();
            try
            {
                using (ArchitectureEntitiesModel ObjEntities = new ArchitectureEntitiesModel())
                {
                    var ClientExpense = new SelectList(ObjEntities.ExpenseListNames.ToList(), "Id", "Description");

                    ViewData["ClientExpense"] = ClientExpense;

                }
                
                string constr = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
                using (SqlConnection con = new SqlConnection(constr))
                {
                    string selectedexpensetype = Request.Form["ExpenseType"].ToString();
                    string query = "Select * from ClientsExpense as C inner join ExpenseListNames as E on E.Id=C.Expensetype where C.Expensetype= " + selectedexpensetype + "";
                    using (SqlCommand cmd = new SqlCommand(query))
                    {
                        cmd.Connection = con;
                        using (SqlDataAdapter sda = new SqlDataAdapter(cmd))
                        {
                            sda.Fill(dt);
                        }

                        ds.Tables.Add(dt);
                    }
                }
                TempData["Heading"] = 7;
            }
            catch { }
         
            return View(ds);
        }


        public ActionResult Recapperclient()
        {
            DataTable dt = new DataTable();
            DataSet ds = new DataSet();
            try {
                string constr = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
                using (SqlConnection con = new SqlConnection(constr))
                {

                    using (ArchitectureEntitiesModel ObjEntities = new ArchitectureEntitiesModel())
                    {
                        var ClientExpense = new SelectList(ObjEntities.ClientsViews.ToList(), "Id", "Name");

                        ViewData["recapperclient"] = ClientExpense;

                    }

                    if (TempData["Isfilter"] == null || TempData["Isfilter"].ToString() == "0")
                    {
                        string query = "Select * from ClientsPayment as P inner join ClientsView as C on C.Id=P.Client";
                        using (SqlCommand cmd = new SqlCommand(query))
                        {
                            cmd.Connection = con;
                            using (SqlDataAdapter sda = new SqlDataAdapter(cmd))
                            {
                                sda.Fill(dt);
                            }

                            ds.Tables.Add(dt);
                        }

                    }
                    else
                    {
                        TempData["Isfilter"] = 0;
                        

                        return View(dsfilter);
                    }


                }
                TempData["Heading"] = 8;

            }
            catch(Exception ex) { }
            
            

            return View(ds);
        }

        [HttpPost]
        public ActionResult Recapperclient(FormCollection form)
        {
            try
            {
                DataTable dt = new DataTable();

                string constr = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
                using (SqlConnection con = new SqlConnection(constr))
                {
                    string selectedclient = Request.Form["Client"].ToString();
                    using (ArchitectureEntitiesModel ObjEntities = new ArchitectureEntitiesModel())
                    {
                        var ClientExpense = new SelectList(ObjEntities.ClientsViews.ToList(), "Id", "Name");

WebApplication1/Views/RecapPages/Recapperclient.cshtml
@using System.Data
@model DataSet
@{
    ViewBag.Title = "Recapperclient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Success"] != null)
{
    <div id="Success">
        <div class="alert alert-success fade show" role="alert">
            @TempData["Success"]
        </div>
    </div>

}
@if (TempData["Error"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Error"]
        </div>
    </div>
}

@if (TempData["Failed"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Failed"]
        </div>
    </div>
}

@using (Html.BeginForm("Recapperclient", "RecapPages", FormMethod.Post))
{
    <div class="tab-content">
        <div class="tab-pane tabs-animation fade show active" id="tab-content-0" role="tabpanel">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <h5 class="card-title">Recap Per Client </h5>
                    <div class="main-card mb-3 card">
                        <div class="card-body">
                            @*<h5 class="card-title"> Add Expense </h5>*@
                            <form class="">
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="position-relative form-group">
                                            @Html.Label("Client", "Select Client")
                                            @Html.DropDownList("Client", (IEnumerable<SelectListItem>)ViewData["recapperclient"], "Select Client", new { @type = "text", placeholder = "Enter Location at here ", @class = "form-control", required = "required" })
                                            @Html.ValidationMessage("Client", "", new { @class = "text-danger" })
                                        </div>
                                    </div>


                                </div>


                                <a href="~/RecapPages/Recapperclient"><button class="mt-2 btn btn-primary">Preview</button></a>
                            </form>
                        </div>
                    </div>
                    <form class="">
                        <div class="form-row">
                            <div class="col-lg-12">
                                <div class="main-card mb-3 card">
                                    <div class="card-body">
                                        @*<h5 class="card-title">Client,s View</h5>*@
                                        <table class="mb-0 table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>Client</th>
                                                    <th>Amount</th>
                                                    <th>Date</th>
                                                    @*<th>Date</th>
                                                        <th>Due Amount</th>
                                                        <th>Full Amount Paid Upto Date</th>*@
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @if (Model.Tables[0].Rows.Count > 0)
                                                {
                                                    foreach (DataRow row in Model.Tables[0].Rows)
                                                    {
                                                        var da = @row["EntryDate"];
                                                        DateTime date = Convert.ToDateTime(da);
                                                        var Date = date.ToString("MMM-dd-yyyy");
                                                        <tr>
                                                            <td>@row["Name"]</td>
                                                            <td>@row["Paid Amount"]</td>
                                                            <td>@Date</td>
                                                        </tr>
                                                    }
                                                }

                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        setTimeout(function () {
            $("#Success").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Error").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Warning").fadeOut();
        }, 5000);
    });

</script>

WebApplication1/Views/RecapPages/Recapperexpensetype.cshtml
@*@model IEnumerable<WebApplication1.ViewModel.RecapperExpensetype>*@
@using System.Data
@model DataSet
@{
    ViewBag.Title = "Recapperexpensetype";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Success"] != null)
{
    <div id="Success">
        <div class="alert alert-success fade show" role="alert">
            @TempData["Success"]
        </div>
    </div>

}
@if (TempData["Error"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Error"]
        </div>
    </div>
}

@if (TempData["Failed"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Failed"]
        </div>
    </div>
}


@using (Html.BeginForm("Recapperexpensetype", "RecapPages", FormMethod.Post))
{
    <div class="tab-content">
        <div class="tab-pane tabs-animation fade show active" id="tab-content-0" role="tabpanel">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <h5 class="card-title">Recap Per Expense Type</h5>
                    <div class="main-card mb-3 card">
                        <div class="card-body">
                            @*<h5 class="card-title"> Add Expense </h5>*@
                            <form class="">
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="position-relative form-group">
                                            @Html.Label("Expense Type", "Select Expense")
                                            @Html.DropDownList("ExpenseType", (IEnumerable<SelectListItem>)ViewData["ClientExpense"], "Select Expense type", new { @type = "text", placeholder = "Enter Location at here ", @class = "form-control", required = "required" })
                                            @Html.ValidationMessage("Expense Type", "", new { @class = "text-danger" })
                                        </div>
                                    </div>


                                </div>


                                <a href="~/RecapPages/Recapperclient"><button class="mt-2 btn btn-primary">Preview</button></a>
                            </form>
                        </div>
                    </div>
                    <form class="">
                        <div class="form-row">
                            <div class="col-lg-12">
                                <div class="main-card mb-3 card">
                                    <div class="card-body">
                                        @*<h5 class="card-title">Client,s View</h5>*@
                                        <table class="mb-0 table table-bordered">
                                            <thead>
                                                <tr>

                                                    <th>Expense Type</th>
                                                    <th>Amount</th>
                                                    <th>Date</th>
                                                    @*<th>Date</th>
                                                        <th>Due Amount</th>
                                                        <th>Full Amount Paid Upto Date</th>*@
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (DataRow row in Model.Tables[0].Rows)
                                                {
                                                        var da = @row["EntryDate"];
                                                        DateTime date = Convert.ToDateTime(da);
                                                        var Date = date.ToString("MMM-dd-yyyy");
                                                    <tr>
                                                        <td>@row["Description"]</td>
                                                        <td>@row["Amount"]</td>
                                                        <td>@Date</td>
                                                    </tr>
                                                }
                                            </tbody>

                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        setTimeout(function () {
            $("#Success").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Error").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Warning").fadeOut();
        }, 5000);
    });

</script>

WebApplication1/Views/RecapPages/Recappermonth.cshtml
@using System.Data
@model DataSet
@{
    ViewBag.Title = "Recappermonth";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Success"] != null)
{
    <div id="Success">
        <div class="alert alert-success fade show" role="alert">
            @TempData["Success"]
        </div>
    </div>

}
@if (TempData["Error"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Error"]
        </div>
    </div>
}

@if (TempData["Failed"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Failed"]
        </div>
    </div>
}

@using (Html.BeginForm("Recappermonth", "RecapPages", FormMethod.Post))
{
    <div class="tab-content">
        <div class="tab-pane tabs-animation fade show active" id="tab-content-0" role="tabpanel">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <h5 class="card-title">Recap Per Month </h5>
                    <div class="main-card mb-3 card">
                        <div class="card-body">
                            @*<h5 class="card-title"> Add Expense </h5>*@
                            <form class="">
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="position-relative form-group">
                                            @Html.Label("Month", "Select Month")
                                            @Html.DropDownList("Month", (IEnumerable<SelectListItem>)ViewData["GetMonth"], "Select Month", new { @type = "text", placeholder = "Enter Month at here ", @class = "form-control", required = "required" })
                                            @Html.ValidationMessage("Month", "", new { @class = "text-danger" })
                                        </div>
                                    </div>


                                </div>


                                <a href="~/RecapPages/Recapperclient"><button class="mt-2 btn btn-primary">Preview</button></a>
                            </form>
                        </div>
                    </div>
                    <form class="">
                        <div class="form-row">
                            <div class="col-lg-12">
                                <div class="main-card mb-3 card">
                                    <div class="card-body">
                                        @*<h5 class="card-title">Client,s View</h5>*@
                                        <table class="mb-0 table table-bordered">
                                            <thead>
                                                <tr>

                                                    <th>Month</th>
                                                    <th>Income</th>
                                                    <th>Expense</th>
                                                    <th>Net Amount</th>
                                                    @*<th>Date</th>
                                                        <th>Due Amount</th>
                                                        <th>Full Amount Paid Upto Date</th>*@
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (DataRow row in Model.Tables[0].Rows)
                                                {
                                                    <tr>
                                                        <td>@row["Month"]</td>
                                                        <td>@row["Income"]</td>
                                                        <td>@row["Expense"]</td>
                                                        <td>@row["NetAmount"]</td>
                                                    </tr>
                                                }

                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

}


<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        setTimeout(function () {
            $("#Success").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Error").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Warning").fadeOut();
        }, 5000);
    });

</script>