WebApplication1/Controllers/MainDashboardController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers
{
    [CheckSession]
    public class MainDashboardController : Controller
    {

        ArchitectureEntitiesModel ObjEntities = new ArchitectureEntitiesModel();
         
        // GET: MainDashboard
        public ActionResult ClientsGridView()
        {
            TempData["Heading"] = 3;
            try {
                using (ArchitectureEntitiesModel ObjEntities = new ArchitectureEntitiesModel())
                {
                    var Eshtriackstype = new SelectList(ObjEntities.EshtiracksTypes.ToList(), "Id", "Description");
                    ViewData["EshtiracksTypes"] = Eshtriackstype;
                }

                var getClientData = ObjEntities.ClientsViews.OrderByDescending(c => c.Id).ToList();
                if (getClientData.Count != 0)
                {
                    List<ClientVM> ClientList = new List<ClientVM>();
                    foreach (var i in getClientData)
                    {
                        ClientVM v = new ClientVM();
                        v.Amount = i.Amount;
                        var getType = ObjEntities.EshtiracksTypes.Where(e => e.Id == i.Type).FirstOrDefault();
                        if (getType != null)
                        {
                            v.Type = getType.Description;
                        }
                        else
                        {
                            v.Type = "General";
                        }
                        v.Id = i.Id;
                        v.Name = i.Name;
                        v.Location = i.Location;
                        v.Date = i.Date;
                        v.FullPaymentuptodate = i.FullPaymentuptodate;
                        v.EntryDate = i.EntryDate;
                        ClientList.Add(v);


                    }
                    TempData["ClientData"] = ClientList;
                    
                }
            }
            catch (Exception ex) { }
            
            return View();
        }

        [HttpPost]
        public ActionResult ClientsGridView(ClientsView clientsview,FormCollection Form)
        {
            try {
                if (ModelState.IsValid)
                {

                    using (ArchitectureEntitiesModel ObjEntities = new ArchitectureEntitiesModel())
                    {
                        clientsview.Date = DateTime.Parse(clientsview.Date.ToShortTimeString());
                        clientsview.FullPaymentuptodate = DateTime.Parse(clientsview.FullPaymentuptodate.ToShortTimeString());
                        clientsview.EntryDate = DateTime.Parse(DateTime.Now.ToShortTimeString());
                        ObjEntities.ClientsViews.Add(clientsview);
                        ObjEntities.SaveChanges();
                        int id = clientsview.Id;
                        if (id > 0)
                        {
                            TempData["Success"] = "Successfully Saved";
                        }
                        else
                        {
                            TempData["Failed"] = "Not Saved";
                        }
                    }
                }
            }
            catch (Exception ex) { }
            
            //TempData["ClientData"] = ObjEntities.ClientsView.ToList();
            return RedirectToAction("ClientsGridView");
        }

        public ActionResult EditClientsGridView(Int32 id)
        {
            var clientsview = new ClientsView();
            try
            {
                clientsview = ObjEntities.ClientsViews.Where(x => x.Id == id).FirstOrDefault();
                DateTime myDateTime = new DateTime();
                if (clientsview != null)
                {
                    ViewBag.Id = id;
                    var Eshtriackstype = new SelectList(ObjEntities.EshtiracksTypes.ToList(), "Id", "Description");
                    ViewData["EshtiracksTypes"] = Eshtriackstype;

                }
                var date = clientsview.Date.ToString();
                if (date != "")
                {
                    myDateTime = Convert.ToDateTime(clientsview.Date.ToString());
                    ViewBag.Tdate = myDateTime.ToString("yyyy-MM-dd");
                }
                date = clientsview.FullPaymentuptodate.ToString();
                if (date != "")
                {
                    myDateTime = Convert.ToDateTime(clientsview.FullPaymentuptodate.ToString());
                    ViewBag.FDate = myDateTime.ToString("yyyy-MM-dd");
                }
                ViewBag.Id = id;
                TempData["Heading"] = 3;
                TempData["Success"] = "Successfully Updated";
            }
            catch(Exception ex) { }
          
            return View(clientsview);
        }

        [HttpPost]
        public ActionResult UpdateClientsGridView(ClientsView clientsview)
        {
            try
            {
                using (ArchitectureEntitiesModel entities = new ArchitectureEntitiesModel())
                {
                    ClientsView updatedclientsview = (from c in entities.ClientsViews
                                                      where c.Id == clientsview.Id
                                                      select c).FirstOrDefault();

                    updatedclientsview.Name = clientsview.Name;
                    updatedclientsview.Location = clientsview.Location;
                    updatedclientsview.Type = clientsview.Type;
                    updatedclientsview.Date = clientsview.Date;
                    updatedclientsview.Amount = clientsview.Amount;
                    updatedclientsview.FullPaymentuptodate = clientsview.FullPaymentuptodate;
                    updatedclientsview.EntryDate = DateTime.Now;
                    entities.SaveChanges();
                    TempData["Success"] = "Successfully Updated";
                }
            }
            catch (Exception ex) { }
           
            return RedirectToAction("ClientsGridView");
        }

        public ActionResult DeleteClient(int? id)
        {
            try
            {
                if (id != null)
                {
                   
                    var clientpayment = ObjEntities.ClientsPayments.SingleOrDefault(e => e.Client == id );
                    if (clientpayment.Id > 0 && int.Parse(clientpayment.Due_Amount) > 0)
                    {
                        TempData["Warning"] = "Cannot Delete Client having due amount.Please Pay Full Due Amount";
                        return RedirectToAction("ClientsGridView");
                    }
                    else
                    {
                        var client = ObjEntities.ClientsViews.SingleOrDefault(e => e.Id == id);
                        if (client != null)
                        {
                            ObjEntities.ClientsViews.Remove(client ?? throw new InvalidOperationException());
                            ObjEntities.SaveChanges();
                            TempData["Success"] = "Successfully deleted";
                            return RedirectToAction("ClientsGridView");
                        }
                    }

                }
            }
            catch(Exception ex) { }
           
            return RedirectToAction("ClientsGridView");
        }

        public ActionResult AddPayments()
        {
            TempData["Heading"] = 4;
            try
            {
                using (ArchitectureEntitiesModel ObjEntities = new ArchitectureEntitiesModel())
                {
                    var Client = new SelectList(ObjEntities.ClientsViews.ToList(), "Id", "Name");
                    var Month = new SelectList(ObjEntities.tblMonths.ToList(), "Id", "Month");
                    ViewData["ClientPayment"] = Client;
                    ViewData["Month"] = Month;
                }
                var getClientPayment = ObjEntities.ClientsPayments.OrderByDescending(p => p.Id).ToList();
                if (getClientPayment.Count != 0)
                {
                    List<ClientPaymentVM> ClientPaymentlist = new List<ClientPaymentVM>();
                    foreach (var i in getClientPayment)
                    {
                        ClientPaymentVM v = new ClientPaymentVM();

                        var getclient = ObjEntities.ClientsViews.Where(e => e.Id == i.Client).FirstOrDefault();
                        //var getmonth = ObjEntities.tblMonth.Where(e => e.Id == i.Month).FirstOrDefault();
                        if (getclient != null)
                        {
                            v.Client = getclient.Name;
                        }
                        else
                        {
                            v.Client = "No Result";
                        }

                        v.Id = i.Id;
                        v.Month = i.Month;
                        v.Due_Amount = i.Due_Amount;
                        v.Paid_Amount = i.Paid_Amount;
                        v.EntryDate = i.EntryDate;
                        ClientPaymentlist.Add(v);


                    }
                    TempData["ClientPaymentData"] = ClientPaymentlist;
                    
                }
                
            }
            catch(Exception ex) { }
           
            return View();
        }

        [HttpPost]
        public ActionResult AddPayments(ClientsPayment clientpayment)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //UpdateClientsPayment(clientpayment.Paid_Amount,clientpayment.Client);

                    using (ArchitectureEntitiesModel ObjEntities = new ArchitectureEntitiesModel())
                    {

WebApplication1/Views/MainDashboard/AddPayments.cshtml
@model WebApplication1.ClientsPayment
@{
    ViewBag.Title = "AddPayments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Success"] != null)
{
    <div id="Success">
        <div class="alert alert-success fade show" role="alert">
            @TempData["Success"]
        </div>
    </div>

}
@if (TempData["Error"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Error"]
        </div>
    </div>
}

@if (TempData["Failed"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Failed"]
        </div>
    </div>
}
@if (TempData["Warning"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Warning"]
        </div>
    </div>
}

@using (Html.BeginForm("AddPayments", "MainDashboard", FormMethod.Post))
{
    <div class="tab-content">
        <div class="tab-pane tabs-animation fade show active" id="tab-content-0" role="tabpanel">
            <div class="main-card mb-3 card">
                <div class="card-body">

                    <h5 class="card-title"> Add Payments </h5>
                    <form class="">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.LabelFor(m => m.Client, "Select Client")
                                    @Html.DropDownListFor(m => m.Client, (SelectList)ViewData["ClientPayment"], "Select Client", new { @type = "text", placeholder = "Enter Location at here ", @class = "form-control", required = "required" })
                                    @Html.ValidationMessageFor(m => m.Client, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.LabelFor(m => m.Month, "Payment for Month")
                                    @Html.TextBoxFor(m => m.Month, " ", new { @type = "Date", placeholder = "Enter Location at here ", @class = "form-control", required = "required" })
                                    @Html.ValidationMessageFor(m => m.Month, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.LabelFor(m => m.Paid_Amount, "Amount")
                                    @Html.TextBoxFor(m => m.Paid_Amount, " ", new { @type = "number", placeholder = "Enter Amount at here ", @class = "form-control", required = "required" })
                                    @Html.ValidationMessageFor(m => m.Paid_Amount, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>



                        <button class="mt-2 btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-12">
                    <div class="main-card mb-3 card">

                        <div class="card-body">
                            <h5 class="card-title">Clients Payment</h5>
                            <div class="table-responsive">
                                <table class="mb-0 table table-bordered">
                                    <thead>
                                        <tr>

                                            <th>Client</th>
                                            <th>Payment for Month</th>
                                            <th>Paid Amount</th>
                                            <th>Due Amount</th>
                                            <th>Payment Date</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (TempData["ClientPaymentData"] != null)
                                        {
                                            foreach (var E in (List<WebApplication1.ViewModel.ClientPaymentVM>)TempData["ClientPaymentData"])
                                            {


                                                <tr>

                                                    <td>@E.Client</td>
                                                    <td>@E.Month.ToString("MMM-yyyy")</td>
                                                    <td>@E.Paid_Amount</td>
                                                    <td>@E.Due_Amount</td>
                                                    <td>@E.EntryDate.ToString("MMM-dd-yyyy")</td>
                                                    @if ((E.Due_Amount.ToString() == "0"))
                                                    {
                                                        <td>
                                                            <label class="statusBtn badge badge-success">
                                                                <i class="fa fa-bell"></i>
                                                            </label>
                                                        </td>
                                                    }
                                                    else
                                                    {
                                                        <td>
                                                            <label class="statusBtn badge badge-danger">
                                                                <i class="fa fa-bell"></i>
                                                            </label>
                                                        </td>
                                                    }



                                                    <td>
                                                        |<a href="@Url.Action("EditClientsPayment", "MainDashboard", new { id = E.Id})"><i class="fa fa-edit text-default"></i></a>|
                                                        |<a href="@Url.Action("DeletePayment", "MainDashboard", new { id = E.Id})"><i class="fa fa-trash text-danger"></i></a>|
                                                    </td>
                                                </tr>
                                            }
                                        }
                                    </tbody>
                                </table>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        setTimeout(function () {
            $("#Success").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Error").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Warning").fadeOut();
        }, 5000);
    });

</script>

WebApplication1/Views/MainDashboard/ChooseExpense.cshtml
@model WebApplication1.ClientsExpense
@{
    ViewBag.Title = "ChooseExpense";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (TempData["Success"] != null)
{
    <div id="Success">
        <div class="alert alert-success fade show" role="alert">
            @TempData["Success"]
        </div>
    </div>

}
@if (TempData["Error"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Error"]
        </div>
    </div>
}

@if (TempData["Failed"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Failed"]
        </div>
    </div>
}
@using (Html.BeginForm("AddExpense", "MainDashboard", FormMethod.Post))
{
    <div class="tab-content">
        <div class="tab-pane tabs-animation fade show active" id="tab-content-0" role="tabpanel">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <h5 class="card-title"> Add Expense </h5>
                   
                    <form class="">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.LabelFor(m => m.Expensetype, "Expense Type")
                                    @Html.DropDownListFor(m => m.Expensetype, (SelectList)ViewData["ClientExpense"], "Select Expense Type", new { @type = "text", placeholder = "Enter Location at here ", @class = "form-control", required = "required" })
                                    @Html.ValidationMessageFor(m => m.Expensetype, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.LabelFor(m => m.MonthDate, "Expense for Month")
                                    @Html.TextBoxFor(m => m.MonthDate, " ", new { @type = "Date", placeholder = "Enter Location at here ", @class = "form-control", required = "required" })
                                    @Html.ValidationMessageFor(m => m.MonthDate, "", new { @class = "text-danger" })

                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.LabelFor(m => m.MonthDate, "Amount")
                                    @Html.TextBoxFor(m => m.Amount, "", new { @type = "number", placeholder = "Enter Amount at here ", @class = "form-control", required = "required" })
                                    @Html.ValidationMessageFor(m => m.Amount, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>


                        <button class="mt-2 btn btn-primary">Add</button>
                    </form>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-12">
                    <div class="main-card mb-3 card">

                        <div class="card-body">
                            <h5 class="card-title">Expenses Payment</h5>
                            <div class="table-responsive">
                                <table class="mb-0 table table-bordered">
                                    <thead>
                                        <tr>

                                            <th>Expense Type</th>
                                            <th>Expense Month</th>
                                            <th>Amount</th>
                                            <th>Entry Date</th>
                                            <th>Action</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (TempData["ClientExpenseData"] != null)
                                        {
                                            foreach (var E in (List<WebApplication1.ViewModel.ClientExpenseVM>)TempData["ClientExpenseData"])
                                            {


                                                <tr>

                                                    <td>@E.Expensetype</td>
                                                    <td>@E.MonthDate.ToString("MMM-yyyy")</td>
                                                    <td>@E.Amount</td>
                                                    <td>@E.EntryDate.ToString("MMM-dd-yyyy")</td>
                                                    <td>
                                                        |<a href="@Url.Action("EditClientsExpenses", "MainDashboard", new { id = E.Id })"><i class="fa fa-edit text-default"></i></a>|
                                                        |<a href="@Url.Action("DeleteClientExpense", "MainDashboard", new { id = E.Id })"><i class="fa fa-trash text-danger"></i></a>|
                                                    </td>
                                                </tr>
                                            }
                                        }
                                    </tbody>
                                </table>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



}



<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        setTimeout(function () {
            $("#Success").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Error").fadeOut();
        }, 5000);
    });

</script>

WebApplication1/Views/MainDashboard/EditClientsExpenses.cshtml
@model WebApplication1.ClientsExpense
@{
    ViewBag.Title = "EditClientsExpenses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Success"] != null)
{
    <div id="Success">
        <div class="alert alert-success fade show" role="alert">
            @TempData["Success"]
        </div>
    </div>

}
@if (TempData["Error"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Error"]
        </div>
    </div>
}

@if (TempData["Failed"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Failed"]
        </div>
    </div>
}

@using (Html.BeginForm("UpdateClientsExpense", "MainDashboard", FormMethod.Post))
{
    <div class="tab-content">
        <div class="tab-pane tabs-animation fade show active" id="tab-content-0" role="tabpanel">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <h5 class="card-title"> Update Expense </h5>
                   
                    <form class="">
                        <div class="form-row">
                            @Html.HiddenFor(m => m.Id)
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.LabelFor(m => m.Expensetype, "Expense Type")
                                    @Html.DropDownListFor(m => m.Expensetype, (SelectList)ViewData["ClientExpense"], "Select Client", new { @type = "text", placeholder = "Enter Location at here ", @class = "form-control", required = "required" })
                                    @Html.ValidationMessageFor(m => m.Expensetype, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.LabelFor(m => m.MonthDate, "Expense for Month")
                                    @Html.TextBoxFor(m => m.MonthDate, " ", new { @type = "Date", placeholder = "Enter Location at here ", @class = "form-control", required = "required" })
                                    @Html.ValidationMessageFor(m => m.MonthDate, "", new { @class = "text-danger" })

                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.LabelFor(m => m.MonthDate, "Amount")
                                    @Html.TextBoxFor(m => m.Amount, "", new { @type = "number", placeholder = "Enter Amount at here ", @class = "form-control", required = "required" })
                                    @Html.ValidationMessageFor(m => m.Amount, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>



                        <button class="mt-2 btn btn-primary">Update</button>
                    </form>
                </div>
            </div>

        </div>
    </div>

}

<script>
    $(document).ready(function () {
        setTimeout(function () {
            $("#Success").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Error").fadeOut();
        }, 5000);
    });

</script>

WebApplication1/Views/MainDashboard/EditClientsPayment.cshtml
@model WebApplication1.ClientsPayment
@{
    ViewBag.Title = "EditClientsPayment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Success"] != null)
{
    <div id="Success">
        <div class="alert alert-success fade show" role="alert">
            @TempData["Success"]
        </div>
    </div>

}
@if (TempData["Error"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Error"]
        </div>
    </div>
}

@if (TempData["Failed"] != null)
{
    <div id="Error">
        <div class="alert alert-danger fade show" role="alert">
            @TempData["Failed"]
        </div>
    </div>
}

@using (Html.BeginForm("UpdateClientsPayment", "MainDashboard", FormMethod.Post))
{
    <div class="tab-content">
        <div class="tab-pane tabs-animation fade show active" id="tab-content-0" role="tabpanel">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <h5 class="card-title"> Update Payments </h5>
                    <form class="">
                        <div class="form-row">
                            @Html.HiddenFor(m => m.Id)
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.LabelFor(m => m.Client, "Select Client")
                                    @Html.DropDownListFor(m => m.Client, (SelectList)ViewData["ClientPayment"], "Select Client", new { @type = "text", placeholder = "Enter Location at here ", @class = "form-control", required = "required" })
                                    @Html.ValidationMessageFor(m => m.Client, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            @*<div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.LabelFor(m => m.Month, "Date")
                                    @Html.TextBoxFor(m => m.Month, " ", new { @type = "Date", placeholder = "Enter Location at here ", @class = "form-control", required = "required" })
                                    @Html.ValidationMessageFor(m => m.Month, "", new { @class = "text-danger" })
                                </div>
                            </div>*@
                            <div class="col-md-6">
                                <div class="position-relative form-group">
                                    @Html.LabelFor(m => m.Paid_Amount, "Amount")
                                    @Html.TextBoxFor(m => m.Paid_Amount, "", new { @type = "number", placeholder = "Enter Amount at here ", @class = "form-control", required = "required" })
                                    @Html.ValidationMessageFor(m => m.Paid_Amount, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>



                        <button class="mt-2 btn btn-primary">Update</button>
                    </form>
                </div>
            </div>

        </div>
    </div>

}


<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        setTimeout(function () {
            $("#Success").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Error").fadeOut();
        }, 5000);
    });
    $(document).ready(function () {
        setTimeout(function () {
            $("#Warning").fadeOut();
        }, 5000);
    });

</script>